### ISSUE TITLE
Optionally include the ceph dashboard with rook

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kURL#372] opened 2020-04-15 01:39 UTC
The Ceph dashboard makes diagnosing ceph issues, and generally monitoring cluster health, far easier. We should support including it with rook.

**Comment by emosbaugh** [comment] 2020-10-15 23:58
This is a duplicate of #210

**Comment by camilamacedo86** [comment] 2022-12-21 08:43
Closing this one as duplicated. However, if you see that it is not, please feel free to re-open.

**Closed by camilamacedo86** 2022-12-21 08:43 UTC
Labels: type::feature
