### ISSUE TITLE
getting error in air-gap install on flannel step--- waiting for Flannel to become healthy Error from server (BadRequest): container "install-cni-plugin" in pod "kube-flannel-ds-z7p52" is waiting to start: PodInitializing An error occurred on line Would you like to provide a support bundle to aid us in avoiding similar errors in the future? (y/N)

### ISSUE THREAD

**Issue by bakudih** [replicatedhq/kURL#4105] opened 2023-02-15 10:29 UTC
how to get through this

**Comment by camilamacedo86** [comment] 2023-02-15 10:35
HI @bakudih,

You might not using the latest version. However, please see that for we are able to help you out when we face problems we need to have further information to be able to reproduce the issue (as requested in the other issue open by you https://github.com/replicatedhq/kURL/issues/4096 ) 

Therefore, could you please provide:

- Please, provide the kURL logs which are under /var/log/kurl. Could you please add them here?
- Please, provide the link used to the install
- Please, let us know if it is a new install or if it is an upgrade
- Also, can you please share the support bundle? It probably was created when the error was faced if say Y I want report the issue. Or you can see https://community.replicated.com/t/kurl-how-can-i-generate-a-support-bundle-when-my-kubernetes-cluster-is-down/911 and attached here the result.

**Comment by camilamacedo86** [comment] 2023-04-25 11:38
Hi @bakudih,

Since the required info has not been provided and it is open without interaction since Feb 15 I am closing this one. However, please feel free to raise new issues if you need. 

Thank you for your attention and time.

**Closed by camilamacedo86** 2023-04-25 11:38 UTC
